FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
about.summary="samtools and bedtools container"

ENV samtools_version=1.11 \
htslib_version=1.11 \
bedtools_version=2.29.2

ENV PACKAGES="procps curl build-essential zlib1g-dev libncurses-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libfindbin-libs-perl" \
PYTHON="python3 python3-pip python3-dev"

ENV PATH=${PATH}:/usr/local/bin/bedtools2/bin

RUN apt-get update \
&& apt-get install -y $PACKAGES $PYTHON \
&& ln -s /usr/bin/python3 /usr/bin/python \
&& curl -fsSL https://github.com/samtools/samtools/archive/${samtools_version}.tar.gz | tar -xz \
&& curl -fsSL https://github.com/samtools/htslib/releases/download/${htslib_version}/htslib-${htslib_version}.tar.bz2 | tar -xj \
&& make -C samtools-${samtools_version} -j HTSDIR=../htslib-${htslib_version} \
&& make -C samtools-${samtools_version} -j HTSDIR=../htslib-${htslib_version} prefix=/usr/local install \
&& rm -r samtools-${samtools_version} \
&& rm -r htslib-${htslib_version} \
&& curl -fsSL https://github.com/arq5x/bedtools2/releases/download/v${bedtools_version}/bedtools-${bedtools_version}.tar.gz | tar -C /usr/local/bin -xz \
&& make -C /usr/local/bin/bedtools2
