FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
software="perl container for json parsing"

ENV PACKAGES="procps curl wget=1.20.1-1.1 build-essential perl libjson-perl cpanminus jq"

RUN apt-get update && apt-get install -y $PACKAGES \
&& cpanm JSON::Create
