FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
about.summary="bwa and samtools container"

ENV samtools_version=1.11 \
htslib_version=1.11 \
minimap2_version=2.17 \
picard_version=2.18.16

ENV PYTHON="python3 python3-pip"

ENV PYTHON_PACKAGES="pysam"

ENV PACKAGES="software-properties-common procps curl wget build-essential zlib1g-dev libncurses-dev libbz2-dev liblzma-dev libcurl4-openssl-dev perl libjson-perl libfindbin-libs-perl cpanminus jq"

RUN apt-get update && apt-get install -y $PACKAGES $PYTHON \
&& ln -s /usr/bin/python3 /usr/bin/python \
&& pip3 install $PYTHON_PACKAGES \
&& cpanm JSON::Create \
&& wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - \
&& add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ \
&& apt-get update && apt-get install -y adoptopenjdk-8-hotspot \
&& curl -fsSL https://github.com/samtools/samtools/archive/${samtools_version}.tar.gz | tar -xz \
&& curl -fsSL https://github.com/samtools/htslib/releases/download/${htslib_version}/htslib-${htslib_version}.tar.bz2 | tar -xj \
&& make -C samtools-${samtools_version} -j HTSDIR=../htslib-${htslib_version} \
&& make -C samtools-${samtools_version} -j HTSDIR=../htslib-${htslib_version} prefix=/usr/local install \
&& rm -r samtools-${samtools_version} \
&& rm -r htslib-${htslib_version} \
&& curl -fsSL minimap2-${minimap2_version}.tar.gz https://github.com/lh3/minimap2/archive/v${minimap2_version}.tar.gz | tar -xz \
&& cd minimap2-${minimap2_version} \
&& make \
&& chmod +x minimap2 \
&& mv minimap2 /usr/local/bin \
&& cd .. \
&& rm -r minimap2-${minimap2_version} \
&& wget https://github.com/broadinstitute/picard/releases/download/${picard_version}/picard.jar -O /usr/local/bin/picard.jar

ENV PICARD_JAR=/usr/local/bin/picard.jar
