FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
about.summary="fqtools container"

ENV fqtools_version=2.3 \
htslib_version=1.11

ENV PACKAGES="procps curl build-essential libz-dev libbz2-dev liblzma-dev libcurl4-openssl-dev autoconf"

ENV PATH=${PATH}:/usr/local/bin/fqtools-${fqtools_version}/bin
ENV LD_LIBRARY_PATH=/usr/local/lib

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& curl -fsSL https://github.com/alastair-droop/fqtools/archive/v${fqtools_version}.tar.gz | tar -C /usr/local/bin -xz \
&& cd /usr/local/bin/fqtools-${fqtools_version} \
&& curl -fsSL https://github.com/samtools/htslib/releases/download/${htslib_version}/htslib-${htslib_version}.tar.bz2 | tar -xj \
&& mv htslib-${htslib_version} htslib \
&& cd htslib \
&& autoreconf -i \
&& ./configure \
&& make \
&& make install \
&& cd .. \
&& make \
&& chmod +x bin/fqtools
