FROM ubuntu:20.04

LABEL maintainer="pricea35@cardiff.ac.uk" \
about.summary="container for the vcf predict workflow"

ENV PACKAGES="procps curl wget git build-essential libhdf5-dev libffi-dev r-base-core jq" \
PYTHON="python3 python3-pip python3-dev"

ENV vcfmix_version=d50267b5448b12072a788e54f9886022c5296e46 \
gumpy_version=1.0.3 \
piezo_version=0.2 \
gnomon_version=1.0.0-alpha.2 \
tuberculosis_amr_catalogues=86a12f8160083ce33e2e11bc6f2934b3bfc3db91

RUN apt-get update \
&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata \
&& apt-get install -y $PACKAGES $PYTHON \
&& apt-get install -y python3-packaging \
&& git clone https://github.com/AlexOrlek/VCFMIX.git \
&& cd VCFMIX \
&& git checkout ${vcfmix_version} \
&& pip3 install --upgrade pip \
&& pip3 install recursive_diff \
&& pip3 install -r requirements.txt \
&& cd ..

RUN curl -fsSL https://github.com/oxfordmmm/gumpy/archive/refs/tags/v${gumpy_version}.tar.gz | tar -xz \
&& cd gumpy-${gumpy_version} \
&& pip3 install . \
&& cd ..

RUN curl -fsSL https://github.com/oxfordmmm/piezo/archive/refs/tags/v${piezo_version}.tar.gz | tar -xz \
&& cd piezo-${piezo_version} \
&& pip3 install . \
&& cd ..

RUN curl -fsSL https://github.com/oxfordmmm/gnomon/archive/refs/tags/v${gnomon_version}.tar.gz | tar -xz \
&& cd gnomon-${gnomon_version} \
&& pip3 install . \
&& cd ..

RUN git clone https://github.com/oxfordmmm/tuberculosis_amr_catalogues.git \
&& cd tuberculosis_amr_catalogues \
&& git checkout ${tuberculosis_amr_catalogues} \
&& cd ..

