FROM debian:buster

LABEL maintainer="pricea35@cardiff.ac.uk" \
about.summary="fastp container"

ENV fastp_version=0.20.1

ENV PACKAGES="procps curl build-essential zlib1g-dev jq"

RUN apt-get update \
&& apt-get install -y $PACKAGES \
&& curl -fsSL https://github.com/OpenGene/fastp/archive/v${fastp_version}.tar.gz | tar -xz \
&& cd fastp-${fastp_version} \
&& make \
&& make install \
&& cd .. \
&& rm -r fastp-${fastp_version}
