name: stub-run
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:
  
jobs:
  
  build:

    runs-on: ubuntu-20.04

    steps:
    
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: checkout playbook
        uses: actions/checkout@v3
        with:
          repository: whalleyt/ansible.nextflow-container
          ref: lodestone

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          options: |
            --verbose
            
      - uses: actions/checkout@v3
      
      - name: Test stub run
        run: |
          nextflow run main.nf -stub -config testing.config
